name: Semgrep

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto --error --exclude apps/api/src/generated
